[project]
name = "tectonics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12, <3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "noise>=1.2.2",
    "numpy>=2.2.2",
    "panel>=1.8.1",
    "pyvista>=0.46.3",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=8.3.4",
    "ruff>=0.9.4",
]
