name: Formatting Jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          pyproject-file: pyproject.toml
          version: "0.5.24"
          checksum: "a0eb614f7fc38a6e14ef1c4819f1f187591db8e0d3c4218dae38b1bd663a00e2"
      - name: Run ruff check
        run: |
          uv run ruff format --check --diff .
  prettier-md:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - shell: bash
        run: npx prettier --parser markdown ./**/*.md -c
  prettier-yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - shell: bash
        run: npx prettier --parser yaml ./**/*.yaml -c
